### ISSUE TITLE
Did you finally get the multi module dependencies working?

### ISSUE THREAD

**Issue by cesards** [danielsanfr/jitpack-test#1]

**Comment by danielsanfr** [comment]
To achieve this I had to create a module that depends on everyone or others.
In the case of this example:
`compile "com.github.danielsanfr.jitpack-test:all:0.0.7"` -> Contains moduleond and moduletwo
`compile "com.github.danielsanfr.jitpack-test:moduleone:0.0.7"` -> Only moduleone
`compile "com.github.danielsanfr.jitpack-test:moduletwo:0.0.7"` -> Only moduletwo

**Comment by cesards** [comment]
Cool! I got it, as well! Thank you so much for your help ;-)

I think the key was tagging a branch in order to get it working:

https://jitpack.io/#cesards/AndroidCommons/0.0.1
